Prevent installation of DevHome and Outlook
ntdevlabs/tiny11builder pull request #203
Opened 2024-06-10 00:18 UTC by marcel-schliwka

Like @MelKyra recommended in issue #199 I created and tested his idea. My Pull Request deletes and adds those four Registry Keys.

2024-08-05 19:49 UTC, tomByrer commented
Banning Outlook is good, but as a webdev, I might use DevHome.  Any reason why I should not?

2024-09-28 23:38 UTC, Kichura approved these changes

2024-11-06 21:36 UTC, Karl-WE commented
related PR #253

2024-11-06 22:33 UTC, Karl-WE commented
agree with @APT-ZERO the goal is a tiny W11. Dev Home certainly bloats it. Same as MS Edge is removed but can be reinstalled with `winget install Microsoft.Edge` among all your prefered apps @tomByrer, which also includes DevHome.

2024-11-06 22:40 UTC, Karl-WE requested changes
same as #211  we shall replace

`> null`

or

`> $null`

with

`| Out-Null`

2024-11-06 23:38 UTC, Karl-WE approved these changes
added line 244 to comply with former Write-Host per section for logging.

2024-11-06 23:38 UTC, Karl-WE commented on tiny11maker.ps1
> +## Prevents installation or DevHome and Outlook
Write-Host "Prevents installation or DevHome and Outlook"

2024-11-06 23:38 UTC, Karl-WE commented on tiny11maker.ps1
> +## Prevents installation or DevHome and Outlook
added to comply with former syntax for logging.

2024-11-07 02:05 UTC, Karl-WE commented
integrated this in PR #268

2024-11-07 15:30 UTC, adrijanh9 commented
Probably should remove "Outlook and Dev Home might reappear after some time" from the readme to reflect this change

2024-11-07 20:31 UTC, Karl-WE commented
It's a puzzle of two things see related / mentioned items. It should not come back as I have tested it.

2024-11-18 12:17 UTC, Karl-WE commented
@marcel-schliwka this one can be closed.
@ntdevlabs 
Solved with #268

2025-02-17 14:56 UTC, Karl-WE commented
/please-close @marcel-schliwka 
see comments above.

2025-03-20 13:24 UTC, closed without merging