Don't create a 'null' file
ntdevlabs/tiny11builder pull request #211
Opened 2024-06-24 12:59 UTC by eugenesvk

As far as I understand, the proper way is to redirect to `$null`, otherwise currently the script creates an actual `null` file

2024-08-10 21:50 UTC, R-udren commented
This one didn't worked for me.

Version of PowerShell: `7.4.4`

```
ParserError: D:\tiny11maker.ps1:45
Line |
  45 |  … ItemType Directory -Force -Path "$ScratchDisk\tiny11\sources" > &null
     |                                                                   ~
     | Missing file specification after redirection operator.
```

```
ParserError: D:\tiny11maker.ps1:45
Line |
  45 |  … -ItemType Directory -Force -Path "$ScratchDisk\tiny11\sources" >&null
     |                                                                    ~
     | Missing file specification after redirection operator.
```

2024-08-11 09:35 UTC, R-udren commented
[This](https://learn.microsoft.com/en-us/powershell/scripting/samples/redirecting-data-with-out---cmdlets?view=powershell-7.4#discarding-output) should work.

2024-08-11 09:47 UTC, eugenesvk commented
>   45 |  … ItemType Directory -Force -Path "$ScratchDisk\tiny11\sources" > &null

where is `&null from` when this PR replaces with `$null`?

2024-08-11 10:22 UTC, R-udren commented
> where is `&null from` when this PR replaces with `$null`?
oohh.. my bad.

2024-11-06 22:36 UTC, Karl-WE commented
tested even shell commands like reg /? | Out-Null will omit output except errors
@eugenesvk

2024-11-06 22:37 UTC, Karl-WE requested changes
please search and replace  
`> null`
`>null`
`> $null`

`| Out-Null`

2024-11-18 12:05 UTC, Karl-WE commented
@eugenesvk this one can be closed.
@ntdevlabs 
Solved with #268

Please watch out, open PRs do not overwrite the changes by Re-adding nul /null commands.

2025-02-17 14:59 UTC, Karl-WE commented
/please-close @eugenesvk

2025-02-17 15:03 UTC, closed without merging